// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: dotenv/config import removed for Docker builds - env vars are provided by Coolify
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
